# ----------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/chdorner/epubinfo
# ----------------------------------------------------------------

language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install bundler

