# ----------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/chdorner/epubinfo
# ----------------------------------------------------------------

language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode

before_install:
  - gem install bundler

